# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: demowebapp

on:
  push:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: testwebappdotnet    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './published'      # set this to the path to your web app project, defaults to the repository root
  AZURE_SUBSCRIPTION_ID: cda81f25-146f-4d17-b774-0f8adf7c1777

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build ./dotnet-demoapp-master/src/dotnet-demoapp.csproj

    - name: publish
      run: dotnet publish ./dotnet-demoapp-master/src/dotnet-demoapp.csproj -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_435FBCD98BDB426EB7CAE5B66E38E637  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
